- hosts: localhost
  become: yes
  tasks:
   - name: Install aptitude using apt
     apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

   - name: Install required system packages
     apt: name={{ item }} state=latest update_cache=yes
     loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

   - name: Add Docker GPG apt Key
     apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
 
   - name: Add Docker Repository
     apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

   - name: Update apt and install docker-ce
     apt: update_cache=yes name=docker-ce state=latest
 
   - name: install certain python modules for docker
     pip:
       name: "{{ item.name }}"
       version: "{{ item.version }}"
       state: present
     with_items:
      - { name: docker, version: 2.7.0 }
## install jenkins

   - name: Ensure jenkins directory on docker host
     file:
       state: directory
       owner: 1000
       group: 1000
       path: /data/jenkins
   
   - name: Ensure copy casc file on the docker volume
     ansible.builtin.copy:            
       src: jenkins/casc.yaml
       dest: /data/jenkins/casc.yaml
       owner: 1000
       group: 1000

       #   - name: Pull the latest official jenkins docker image
       # docker_image:
       #name: "mehmetyazicioglu/jenkins_ab_project:1.2"
       #source: pull
   - name: Create a container from the jenkins docker image
     docker_container:
       name: "jenkins-server"
       image: "mehmetyazicioglu/jenkins_ab_project:1.2"
       ports:
          - "8080:8080"
          - "50000:50000"
       volumes:
          - "/data/jenkins:/var/jenkins_home"
       env:
          JENKINS_ADMIN_ID: "{{ admin_id }}"
          JENKINS_ADMIN_PASSWORD: "{{ password }}"
       state: started
       recreate: no
